### ISSUE TITLE
Update Razor Page for Event Accept/Reject for rejection to display a dropdown list (generated via AJAX) from the rejection reasons table or a small text field to provide a reason not listed for rejection.

### ISSUE THREAD

**Issue by ABWeb-Dev** [Cascadia-Connections/campus-guidebook#13]
Issue: Format the Razor Page to be responsive to the Administrator's Rejection decision. If selected, the administrator will be able to enter the reason for rejection of the event.

DOD: An administrator is able to submit the reason they did not approve the event and have it be successfully stored in a database table.

Additional: Ajax functionality for drop down list to display existing reasons for rejection, cut down on redundancy.

**Comment by MicahJCave** [comment]
This was finished so I'm closing the issue. It's been merged with develop already.
