### ISSUE TITLE
Create table for rejection events. Link to events table many-to-many relationship.

### ISSUE THREAD

**Issue by TKopp5566447733882299** [Cascadia-Connections/campus-guidebook#14]
DOD: Rejection information can be stored in this table. Manny reasons can be applied to one event and many events can be applied to one event.

Each reason for the rejection of an event will be created into this database. When an event is being rejected, a few previous reasons will be given and can be applied to an event to state why it was rejected.

**Comment by MicahJCave** [comment]
This is finished
