### ISSUE TITLE
Style changes to the view and model remake

### ISSUE THREAD

**Issue by TKopp5566447733882299** [Cascadia-Connections/campus-guidebook#17]
DoD: Change the Event Response layout to now show the title named Requested Event instead of pending. Then change the column to now show : Event Name, club name, event date,  event location, event description, img. Then in the dropdown we should have 3 options listed in the following order: approved, request change, denied. Then add in a textbox with submit if it hasn't been added already. If a textbox has been added then something MUST be added in the textbox.

**Comment by MicahJCave** [comment]
This is finished
