### ISSUE TITLE
Admin and the Event Planner log ins need to be created

### ISSUE THREAD

**Issue by Evachacim** [Cascadia-Connections/campus-guidebook#19]
DoD: After clicking the link to create a profile, then it should be recorded in the Database. They should have an email and password as well as a Username. Then they should be able to log in and either manage events as the admin or request events as the planner.

**Comment by MicahJCave** [comment]
Added in the scaffolding from Visual Studio and added in migrations to create the AppIdentity table to record any account created when registering an account through the web app. The admin is now able to approve/reject any events as well as being able to edit an event.
